### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by felipejoribeiro** [fike/horusec-action#5]
I don´t  know if i'm doing something wrong, but here goes the yml:

```
name: Horusec report
on: pull_request

jobs:
  ckecking_code:
    runs-on: ubuntu-latest
    name: Horusec scan
    steps:
      - uses: actions/checkout@v2
      - name: Run Horusec
        id: run_horusec
        uses: fike/horusec-action@v0.1
        with:
          arguments: -p="./" -a="${{ secrets.HORUSEC_TOKEN }}" -u="${{ secrets.HORUSEC_URL }}" 

```

And the error message;

```
...
/usr/local/bin/horusec: 1: Syntax error: redirection unexpected
/usr/local/bin/horusec: 1: Syntax error: redirection unexpected
```

**Comment by fike** [comment]
Hey @felipejoribeiro! 

Thank you for reporting that. Can you try to put "**-p**" as an argument? New Horusec versions need to explicit pass the directory target like that.

```
name: Horusec report
on: pull_request

jobs:
  ckecking_code:
    runs-on: ubuntu-latest
    name: Horusec scan
    steps:
      - uses: actions/checkout@v2
      - name: Run Horusec
        id: run_horusec
        uses: fike/horusec-action@v0.1
        with:
          arguments: -p="./" -a="${{ secrets.HORUSEC_TOKEN }}" -u="${{ secrets.HORUSEC_URL }}"  -p .
```
